name: SonarQube Scan

on:
  push:
    branches:
      - master 

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt' 
          java-version: '11'  

      - name: SonarQube Scan
        run: |
          ./gradlew sonarqube  
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}